Repository scipy/scipy-stubs, pull requests merged in 2025-02, with the labels that each got.

#443 ⬆️ upgrade the development dependencies
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: meta: deps, meta: chore

#444 🔧 `.toml` auto-format config for vscode users
  .vscode/extensions.json
  .vscode/settings.json
  pyproject.toml
  tox.toml
Labels: meta: DX, meta: style

#445 📝 streamlined contributing guide
  CONTRIBUTING.md
Labels: meta: docs

#446 🚚 change `jorenham/scipy-stubs` refs to `scipy/scipy-stubs`
  CONTRIBUTING.md
  README.md
  pyproject.toml
  scipy-stubs/fft/_realtransforms.pyi
  scipy-stubs/linalg/_decomp.pyi
Labels: meta: chore

#448 Bugfix: Add plain number option for find_peaks argument prominence
  scipy-stubs/signal/_peak_finding.pyi
Labels: scipy.signal, stubs: fix

#451 Bugfix: Make `optimizer` argument optional in `scipy.stats.rv_continuous.fit()`
  scipy-stubs/stats/_distn_infrastructure.pyi
Labels: scipy.stats, stubs: fix

#452 🔨 use `uv` as source of python versions
  .github/workflows/ci.yml
  scripts/generate_matrix.py
Labels: meta: CI, topic: uv

#449 📌 bump `optype` to `0.9.1`
  pyproject.toml
  uv.lock
Labels: meta: deps, topic: optype

#454 ⬆️ bump `basedpyright` to `1.27.1`, `ruff` to `0.9.6`
  .pre-commit-config.yaml
  pyproject.toml
  scipy-stubs/special/_ufuncs.pyi
  scipy-stubs/stats/_new_distributions.pyi
  uv.lock
Labels: meta: deps, meta: chore

#456 📌 SciPy 1.15.2
  .pre-commit-config.yaml
  pyproject.toml
  scipy-stubs/sparse/linalg/__init__.pyi
  scipy-stubs/sparse/linalg/_dsolve/__init__.pyi
  scipy-stubs/version.pyi
  uv.lock
Labels: meta: deps, topic: upstream release, scipy.version

#457 ✨ `stats.zmap`: accept complex input and basic shape-typing
  scipy-stubs/stats/_stats_py.pyi
Labels: scipy.stats, stubs: improvement, topic: upstream release, stubs: api change

#458 🔖 prepare for further development
  pyproject.toml
  uv.lock
Labels: meta: chore

#460 ⬆️ bump `ruff` to `0.9.7`
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: meta: deps, meta: chore

#461 💄 `add-trailing-comma`
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  codegen/mods.py
  scipy-stubs/interpolate/dfitpack.pyi
  scipy-stubs/interpolate/interpnd.pyi
  scipy-stubs/sparse/_construct.pyi
  scipy-stubs/spatial/distance.pyi
  scipy-stubs/special/_basic.pyi
  scipy-stubs/stats/_stats_py.pyi
Labels: meta: CI, meta: style

#462 🔥 remove the codemods
  .libcst.codemod.yaml
  codegen/README.md
  codegen/__init__.py
  codegen/mods.py
  pyproject.toml
  uv.lock
Labels: meta: codemods

#463 🔧 fix the `add-trailing-comma` hook to also work on `.pyi`
  .pre-commit-config.yaml
Labels: meta: DX
