Repository scipy/scipy-stubs, pull requests merged in 2025-03, with the labels that each got.

#466 ⬆️ `basedpyright 0.28.1` and `ruff 0.9.9`
  .pre-commit-config.yaml
  pyproject.toml
  uv.lock
Labels: meta: deps

#467 🐛 `optimize`: allow calling `minimize_scalar` without a `bracket`
  scipy-stubs/optimize/_minimize.pyi
  tests/optimize/minimize_scalar.pyi
Labels: scipy.optimize, stubs: improvement, stubs: fix

#468 📝 add a "typed" badge
  README.md
  pyproject.toml
Labels: meta: docs

#469 🔥 remove pre-commit
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  pyproject.toml
  tox.toml
Labels: meta: CI, meta: DX

#470 🐛 `spatial.transform`: accept proper Euler angles in `Rotation.as_euler`
  scipy-stubs/spatial/transform/_rotation.pyi
Labels: scipy.spatial, stubs: fix

#476 🐛 `scipy.interpolate`: accept scalar input in `BSpline.__call__`
  scipy-stubs/interpolate/_bsplines.pyi
  tests/interpolate/bsplines.pyi
Labels: scipy.interpolate, stubs: fix

#479 📌 restore `basedmypy` to its former glory
  .vscode/settings.json
  pyproject.toml
  scipy-stubs/optimize/cobyla.pyi
  scipy-stubs/optimize/lbfgsb.pyi
  scipy-stubs/optimize/minpack.pyi
  scipy-stubs/optimize/optimize.pyi
  scipy-stubs/optimize/slsqp.pyi
  scipy-stubs/optimize/tnc.pyi
  scripts/generate_matrix.py
  uv.lock
Labels: meta: DX, meta: deps

#478 🐛 `scipy.interpolate`: accept scalar input in `__call__` methods
  scipy-stubs/interpolate/_interpnd.pyi
  scipy-stubs/interpolate/_interpolate.pyi
  scipy-stubs/interpolate/_polyint.pyi
  scipy-stubs/interpolate/_rbf.pyi
Labels: scipy.interpolate, stubs: fix

#481 📌 upgrade `optype` to `0.9.2`
  pyproject.toml
  uv.lock
Labels: meta: deps, topic: optype

#482 👷 ensure `pyright` compatibility
  .github/workflows/ci.yml
  pyproject.toml
  scipy-stubs/sparse/_base.pyi
  scipy-stubs/sparse/_matrix.pyi
  scipy-stubs/sparse/linalg/_interface.pyi
  scipy-stubs/stats/_distribution_infrastructure.pyi
Labels: meta: CI, meta: chore

#483 🔧 adjust `basedmypy` config for `mypy` compat
  pyproject.toml
  scipy-stubs/optimize/_nonlin.pyi
  scipy-stubs/optimize/cobyla.pyi
  scipy-stubs/optimize/lbfgsb.pyi
  scipy-stubs/optimize/minpack.pyi
  scipy-stubs/optimize/optimize.pyi
  scipy-stubs/optimize/slsqp.pyi
  scipy-stubs/optimize/tnc.pyi
  scipy-stubs/special/cython_special.pyi
  scipy-stubs/stats/_distribution_infrastructure.pyi
Labels: meta: chore

#484 ⬆️ bump `ruff` to `0.11.0`
  pyproject.toml
  uv.lock
Labels: meta: deps

#485 🔧 fix vscode settings syntax
  .vscode/settings.json
Labels: meta: style

#486 🔧 remove `files` from `[tool.mypy]`
  pyproject.toml
Labels: meta: chore

#489 ⬆️ update development dependencies
  pyproject.toml
  uv.lock
Labels: meta: deps

#490 📌 bump `optype` to `0.9.3`
  pyproject.toml
  scipy-stubs/optimize/_slsqp_py.pyi
  scipy-stubs/optimize/_zeros_py.pyi
  uv.lock
Labels: meta: deps, topic: optype

#491 🔧 adjust pyright config for `optype.numpy` compatibility
  pyproject.toml
  scipy-stubs/special/_basic.pyi
Labels: stubs: fix, topic: optype
