Repository scipy/scipy-stubs, pull requests merged in 2025-10, with the labels that each got.

#908 🐛 missing `__slots__`
  scipy-stubs/_lib/_util.pyi
  scipy-stubs/interpolate/_interpolate.pyi
  scipy-stubs/io/_mmio.pyi
Labels: scipy._lib, scipy.interpolate, scipy.io, is: fix

#910 📝 Add bashtage/linearmodels to the list of dependents
  README.md
Labels: topic: documentation, is: chore

#911 👷 validate slots and defaults using stubdefaulter
  .github/workflows/ci.yml
  pyproject.toml
  uv.lock
Labels: is: feature, tool: github actions, topic: testing, tool: tox

#913 🔥 remove unused script and comments
  scripts/generate_matrix.py
  scripts/scipy_usage.py
Labels: topic: code style, is: refactor

#914 📝 Add theislab/anndata2ri to the list of dependents
  README.md
  pyproject.toml
Labels: topic: documentation, is: chore

#915 👷 typetest with Python 3.14
  .github/workflows/ci.yml
Labels: tool: github actions, topic: testing, is: chore

#916 🐛 `io`: Fix wrong return type on `scipy.io.wavfile`
  scipy-stubs/io/wavfile.pyi
Labels: scipy.io, is: fix

#920 ⬆️ bump `pyrefly` to `0.36.1`
  pyproject.toml
  scipy-stubs/fft/_backend.pyi
  scipy-stubs/sparse/_dok.pyi
  scipy-stubs/stats/_resampling.pyi
  scripts/scipy_usage.py
  tests/stats/test__entropy.pyi
  uv.lock
Labels: topic: dependencies, is: chore

#922 ⬆️ bump `ruff` to `0.14.0`
  pyproject.toml
  scipy-stubs/optimize/_lbfgsb_py.pyi
  scipy-stubs/spatial/_ckdtree.pyi
  uv.lock
Labels: topic: dependencies, is: chore

#923 ⬆️ bump `uv_build` to `0.8.24`
  pyproject.toml
Labels: topic: dependencies, is: chore

#924 🔖 prepare for further development
  pyproject.toml
  uv.lock
Labels: is: chore

#926 🔖 prepare for further development
  pyproject.toml
  uv.lock
Labels: is: chore

#927 🚑 fix `optype` upper bound (again)
  pyproject.toml
  uv.lock
Labels: is: fix

#928 ⬆️ bump `uv_build` to `0.9.0`
  pyproject.toml
Labels: topic: dependencies, is: chore, tool: uv

#929 ⬆️ bump `astral-sh/setup-uv` to `v7.0.0`
  .github/workflows/ci.yml
  .github/workflows/mypy_primer.yml
  .github/workflows/mypy_primer_comment.yml
  .github/workflows/publish-pypi.yml
Labels: tool: github actions, topic: dependencies, is: chore
